### ISSUE TITLE
Response body

### ISSUE THREAD

**Issue by piv199** [konkab/AlamofireNetworkActivityLogger#1]
Are there any way to print response of the request?

**Comment by konkab** [comment]
@piv199 Currently there is no support for printing response body.

**Comment by piv199** [comment]
@konkab Hm, it seems it could be done through `NSURLConnectionDelegate`

Could you take a look how it is done in [Reqres](https://github.com/AckeeCZ/Reqres/blob/master/Reqres/Classes/Reqres.swift)

**Comment by konkab** [comment]
@piv199 I have implemented this in the latest 2.2.0 release.
