### ISSUE TITLE
Incompatibility with Xcode 10.2 (Swift 5)

### ISSUE THREAD

**Issue by lnfnunes** [konkab/AlamofireNetworkActivityLogger#19]
Couldn't compile in Xcode 10.2 (Swift 5) due to version incompatibility

-> Related (Alamofire resolution): https://github.com/Alamofire/Alamofire/issues/2761

**Comment by donpironet** [comment]
+1

**Comment by sebastienkb** [comment]
+1

**Comment by konkab** [comment]
Should be fixed in the latest release.
