### ISSUE TITLE
Threading Hang

### ISSUE THREAD

**Issue by fdstevex** [konkab/AlamofireNetworkActivityLogger#21]
Hi - I don't know exactly what the problem is here but I wanted to mention a hang I was experiencing and how I fixed it.

I was enabling logging in `didFinishLaunchingWithOptions` and experiencing a hang only when launching on a real device, and only when not in a debugger.  

Attaching Xcode to the hung app would wake the app up.  Strange. Figured it might be threading related.  A number of network requests fire at startup so there's a fair bit of activity on a variety of threads coming in to the logger.

I put the entire body of `networkRequestDidStart` and `networkRequestDidComplete` inside an `OperationQueue.main.addOperation`.  The hangs stopped when I did this.

This is probably not be the best solution, but I didn't get far enough to determine which code was causing the hang.

**Comment by konkab** [comment]
Fixed in latest 3.0.0 release.
