### ISSUE TITLE
Alamofire 5

### ISSUE THREAD

**Issue by danipralea** [konkab/AlamofireNetworkActivityLogger#22]
Hello.
Is this going to be supported anytime soon?

Thanks,
Dan.

**Comment by aletz** [comment]
X2

**Comment by Vuong-Dao** [comment]
I have the same concern. Will we support the latest Alamofire 5?

**Comment by BurakDizlek** [comment]
I had to remove because of that.

**Comment by konkab** [comment]
Release Alamofire 5 support in 3.0.0.
