### ISSUE TITLE
Xcode 11: Swift Package Manager Support

### ISSUE THREAD

**Issue by matgar26** [konkab/AlamofireNetworkActivityLogger#23]
It would be great to be able to install this using Xcode 11's SPM.

**Comment by konkab** [comment]
Yeah, will add support soon.

**Comment by armintelker** [comment]
I would love this.

**Comment by armintelker** [comment]
What is the progress here?

**Comment by rynaardb** [comment]
Is there any reason why https://github.com/konkab/AlamofireNetworkActivityLogger/pull/26/ cannot be merged already?

**Comment by konkab** [comment]
Merged #26
