### ISSUE TITLE
Crash on Xcode 11.2.1

### ISSUE THREAD

**Issue by Vuong-Dao** [konkab/AlamofireNetworkActivityLogger#25]
I usually get crash on this line
<img width="896" alt="Screen Shot 2019-11-24 at 9 53 11 AM" src="https://user-images.githubusercontent.com/26237667/69488764-704ef380-0ea0-11ea-9025-8b4c41601b7f.png">

Xcode Version: 11.2.1 (11B500)
AlamofireNetworkActivityLogger (2.4.0)

**Comment by kainoffke** [comment]
I am facing the same issue. 

It seems to happen when a RequestRetrier is invoked after receiving an error on the first try.

**Comment by liltimtim** [comment]
Same issue

<img width="980" alt="Screen Shot 2019-12-27 at 11 35 53 AM" src="https://user-images.githubusercontent.com/4106065/71524828-3c029480-289d-11ea-9936-30a195dcd93f.png">

**Comment by tony-hoang999** [comment]
Same here. The crashes happen quite often at that line of code

**Comment by JensonK** [comment]
Here is my fix to this issue. If you don't have to use 2.4.0, go with 3.0.0, it's already fixed there.

[Issue25.patch.txt](https://github.com/konkab/AlamofireNetworkActivityLogger/files/4700444/Issue25.patch.txt)

**Comment by konkab** [comment]
Closing this issue because I'm supporting only latest version.
