### ISSUE TITLE
Update Alamofire dependency to 5.0

### ISSUE THREAD

**Issue by tony-hoang999** [konkab/AlamofireNetworkActivityLogger#27]
Please help updating pod spec file to use Alamofire 5.0. Thank you!

**Comment by kamendo** [comment]
the source code is just 1 file, just copy paste it to your project :)

**Comment by konkab** [comment]
Sorry for keep you all waiting. This issue was resolved in 3.4.0.

**Comment by salientsysios** [comment]
Awesome. Thanks @konkab !
