### ISSUE TITLE
Not able to build via Cathage

### ISSUE THREAD

**Issue by radekwilczak** [konkab/AlamofireNetworkActivityLogger#3]
While runing
`carthage update AlamofireNetworkActivityLogger`
I'm getting
`*** Skipped building AlamofireNetworkActivityLogger due to the error:
Dependency "AlamofireNetworkActivityLogger" has no shared framework schemes`

any ideas?

**Comment by sohayb** [comment]
Any update on this @konkab

**Comment by pablog** [comment]
@radekwilczak @sohayb Just add master branch to the Cartfile:

`github "konkab/AlamofireNetworkActivityLogger" "master"`

It should be nice to add a new release adding fixing this @konkab
